INSERT INTO base.tb_ifeb_bi_event(event_cod, event_name, collection) VALUES ( 0,trim(' Por tiempo de lectura'), 'TbBscResultStandardLocation');
INSERT INTO base.tb_ifeb_bi_event(event_cod, event_name, collection) VALUES ( 1,trim(' Panico '), 'TbEbrsPanic');
INSERT INTO base.tb_ifeb_bi_event(event_cod, event_name, collection) VALUES ( 2,trim(' Enganche '), 'TbEbrsHitch');
INSERT INTO base.tb_ifeb_bi_event(event_cod, event_name, collection) VALUES ( 3,trim(' Pta cabina '), 'TbEbrsDigitalInputsCabinDoor');
INSERT INTO base.tb_ifeb_bi_event(event_cod, event_name, collection) VALUES ( 4,trim(' Apertura Puerta Carga'), 'TbEbrsDigitalInputsOpeningLoadingDoor');
INSERT INTO base.tb_ifeb_bi_event(event_cod, event_name, collection) VALUES ( 5,trim('Falla en gps'), 'TbEbrsGpsFailure');
INSERT INTO base.tb_ifeb_bi_event(event_cod, event_name, collection) VALUES ( 6,trim('Fallo de bateria principal'), 'TbEbrsMainBatteryFailure');
INSERT INTO base.tb_ifeb_bi_event(event_cod, event_name, collection) VALUES ( 7,trim('Exceso de velocidad'), 'TbEbrsSpeeding');
INSERT INTO base.tb_ifeb_bi_event(event_cod, event_name, collection) VALUES ( 8,trim(' Fin Exceso de Velocidad'), 'TbEbrsEndSpeeding');
INSERT INTO base.tb_ifeb_bi_event(event_cod, event_name, collection) VALUES ( 9,trim('Interrogación posición'), 'TbEbrsPositionInterrogation');
INSERT INTO base.tb_ifeb_bi_event(event_cod, event_name, collection) VALUES ( 10,trim(' Cambio de Curso'), 'TbEbrsCourseChange');
INSERT INTO base.tb_ifeb_bi_event(event_cod, event_name, collection) VALUES ( 11,trim('Interrogación programación SMS'), 'TbEbrsSmsProgrammingInterrogation');
INSERT INTO base.tb_ifeb_bi_event(event_cod, event_name, collection) VALUES ( 12,trim('Encendido del vehículo'), 'TbEbrsEventIgnitionOnVehicle');
INSERT INTO base.tb_ifeb_bi_event(event_cod, event_name, collection) VALUES ( 13,trim('Apagado del vehículo'), 'TbEbrsEventIgnitionOffVehicle');
INSERT INTO base.tb_ifeb_bi_event(event_cod, event_name, collection) VALUES ( 14,trim('Soobrepaso límite superior ADC1'), 'TbEbrsUpperLimitOverrunAdc1');
INSERT INTO base.tb_ifeb_bi_event(event_cod, event_name, collection) VALUES ( 15,trim('Soobrepaso límite inferior ADC1'), 'TbEbrsLowerLimitOverpassAdc1');
INSERT INTO base.tb_ifeb_bi_event(event_cod, event_name, collection) VALUES ( 16,trim('Soobrepaso límite superior ADC2'), 'TbEbrsUpperLimitOverrunAdc2');
INSERT INTO base.tb_ifeb_bi_event(event_cod, event_name, collection) VALUES ( 17,trim('Soobrepaso límite inferior ADC2'), 'TbEbrsLowerLimitOverpassAdc2');
INSERT INTO base.tb_ifeb_bi_event(event_cod, event_name, collection) VALUES ( 18,trim('Ingreso a'), 'TbEbrsIncomeTo');
INSERT INTO base.tb_ifeb_bi_event(event_cod, event_name, collection) VALUES ( 19,trim('Salida de'), 'TbEbrsExitGeofence');
INSERT INTO base.tb_ifeb_bi_event(event_cod, event_name, collection) VALUES ( 20,trim(' Detección de Curva Brusca'), 'TbEbrsBruscaCurveDetection');
INSERT INTO base.tb_ifeb_bi_event(event_cod, event_name, collection) VALUES ( 21,trim('Reset'), 'TbEbrsWatchdogReboot');
INSERT INTO base.tb_ifeb_bi_event(event_cod, event_name, collection) VALUES ( 22,trim('Control de audio'), 'TbEbrsAudioControl');
INSERT INTO base.tb_ifeb_bi_event(event_cod, event_name, collection) VALUES ( 23,trim('Llamada conversación'), 'TbEbrsCallComversation');
INSERT INTO base.tb_ifeb_bi_event(event_cod, event_name, collection) VALUES ( 24,trim('Autoreporte'), 'TbEbrsAutoreporte');
INSERT INTO base.tb_ifeb_bi_event(event_cod, event_name, collection) VALUES ( 25,trim('Trailer ID'), 'TbEbrsTrailerId');
INSERT INTO base.tb_ifeb_bi_event(event_cod, event_name, collection) VALUES ( 26,trim('Enganche ti'), 'TbEbrsHitchTi');
INSERT INTO base.tb_ifeb_bi_event(event_cod, event_name, collection) VALUES ( 27,trim('Desenganche'), 'TbEbrsDisengagement');
INSERT INTO base.tb_ifeb_bi_event(event_cod, event_name, collection) VALUES ( 28,trim('Paquete satelital'), 'TbEbrsSatellitePackage');
INSERT INTO base.tb_ifeb_bi_event(event_cod, event_name, collection) VALUES ( 29,trim('Interrogación satelital'), 'TbEbrsSatelliteInterrogation');
INSERT INTO base.tb_ifeb_bi_event(event_cod, event_name, collection) VALUES ( 30,trim('Paquete inicial conduse'), 'TbEbrsInitialPackageConduse');
INSERT INTO base.tb_ifeb_bi_event(event_cod, event_name, collection) VALUES ( 31,trim('Datos conduse'), 'TbEbrsDataConduse');
INSERT INTO base.tb_ifeb_bi_event(event_cod, event_name, collection) VALUES ( 32,trim('Confirmación de recepción de pánico'), 'TbEbrsPanicReceivingConfirmation');
INSERT INTO base.tb_ifeb_bi_event(event_cod, event_name, collection) VALUES ( 33,trim('Petición de hora'), 'TbEbrsRequestTime');
INSERT INTO base.tb_ifeb_bi_event(event_cod, event_name, collection) VALUES ( 34,trim('Crash'), 'TbEbrsCrash');
INSERT INTO base.tb_ifeb_bi_event(event_cod, event_name, collection) VALUES ( 35,trim('Kilometraje'), 'TbEbrsMileage');
INSERT INTO base.tb_ifeb_bi_event(event_cod, event_name, collection) VALUES ( 36,trim('Paquete sensor'), 'TbEbrsPackageSensor');
INSERT INTO base.tb_ifeb_bi_event(event_cod, event_name, collection) VALUES ( 37,trim(' Puerta carga abierta '), 'TbEbrsDigitalInputsCabinDoorOpen');
INSERT INTO base.tb_ifeb_bi_event(event_cod, event_name, collection) VALUES ( 38,trim(' Puerta carga cerrada '), 'TbEbrsDigitalInputsCabinDoorClose');
INSERT INTO base.tb_ifeb_bi_event(event_cod, event_name, collection) VALUES ( 39,trim('Lectura por distancia'), 'TbEbrsReadForDistance');
INSERT INTO base.tb_ifeb_bi_event(event_cod, event_name, collection) VALUES ( 40,trim('Fallo de bateria backup'), 'TbEbrsBackupBatteryFailure');
INSERT INTO base.tb_ifeb_bi_event(event_cod, event_name, collection) VALUES ( 41,trim(' Excede Actividad Continua'), 'TbEbrsExceedsContinuousActivity');
INSERT INTO base.tb_ifeb_bi_event(event_cod, event_name, collection) VALUES ( 42,trim('Reservado'), 'TbEbrsReserved');
INSERT INTO base.tb_ifeb_bi_event(event_cod, event_name, collection) VALUES ( 43,trim(' Bloqueo Seguros'), 'TbEbrsSecureLock');
INSERT INTO base.tb_ifeb_bi_event(event_cod, event_name, collection) VALUES ( 44,trim(' Desbloqueo Seguros '), 'TbEbrsUnlockInsurance');
INSERT INTO base.tb_ifeb_bi_event(event_cod, event_name, collection) VALUES ( 45,trim('Apagado remoto sms'), 'TbEbrsOffRemoteSms');
INSERT INTO base.tb_ifeb_bi_event(event_cod, event_name, collection) VALUES ( 46,trim('Habilitado encendido sms'), 'TbEbrsEnabledOnSms');
INSERT INTO base.tb_ifeb_bi_event(event_cod, event_name, collection) VALUES ( 47,trim('Interrogación posición + INT'), 'TbEbrsPositionInterrogationInt');
INSERT INTO base.tb_ifeb_bi_event(event_cod, event_name, collection) VALUES ( 48,trim('Fallo accesorios'), 'TbEbrsAccessoryFailure');
INSERT INTO base.tb_ifeb_bi_event(event_cod, event_name, collection) VALUES ( 49,trim(' Activacion alarma'), 'TbEbrsAlarmActivation');
INSERT INTO base.tb_ifeb_bi_event(event_cod, event_name, collection) VALUES ( 50,trim('LBS'), 'TbEbrsLbs');
INSERT INTO base.tb_ifeb_bi_event(event_cod, event_name, collection) VALUES ( 51,trim('Conductor no valido'), 'TbEbrsUnauthorizedDriver');
INSERT INTO base.tb_ifeb_bi_event(event_cod, event_name, collection) VALUES ( 52,trim('Movimiento ilegal'), 'TbEbrsVehicleCrane');
INSERT INTO base.tb_ifeb_bi_event(event_cod, event_name, collection) VALUES ( 53,trim(' Luces encendidas '), 'TbEbrsLightOn');
INSERT INTO base.tb_ifeb_bi_event(event_cod, event_name, collection) VALUES ( 54,trim('Entrada inalambrica 1 abierta'), 'TbEbrsWirelessOneOpen');
INSERT INTO base.tb_ifeb_bi_event(event_cod, event_name, collection) VALUES ( 55,trim('Entrada inalambrica 1 cerrada'), 'TbEbrsWirelessOneClose');
INSERT INTO base.tb_ifeb_bi_event(event_cod, event_name, collection) VALUES ( 56,trim('Entrada inalambrica 2 abierta'), 'TbEbrsWirelessInputTwoOpen');
INSERT INTO base.tb_ifeb_bi_event(event_cod, event_name, collection) VALUES ( 57,trim('Entrada inalambrica 2 cerrada'), 'TbEbrsWirelessInputTwoClose');
INSERT INTO base.tb_ifeb_bi_event(event_cod, event_name, collection) VALUES ( 58,trim('Autoreporte 2'), 'TbEbrsAutoreporteTwo');
INSERT INTO base.tb_ifeb_bi_event(event_cod, event_name, collection) VALUES ( 59,trim('Programación Sincronismo Ciclado'), 'TbEbrsProgrammingSincronismo');
INSERT INTO base.tb_ifeb_bi_event(event_cod, event_name, collection) VALUES ( 60,trim('Reporte de variables de ciclado'), 'TbEbrsReportingOfCyclicVariables');
INSERT INTO base.tb_ifeb_bi_event(event_cod, event_name, collection) VALUES ( 61,trim('Inicio movimiento'), 'TbEbrsHomeMovement');
INSERT INTO base.tb_ifeb_bi_event(event_cod, event_name, collection) VALUES ( 62,trim(' Fin movimiento '), 'TbEbrsEndMovement');
INSERT INTO base.tb_ifeb_bi_event(event_cod, event_name, collection) VALUES ( 64,trim('Programación CP'), 'TbEbrsProgrammingCp');
INSERT INTO base.tb_ifeb_bi_event(event_cod, event_name, collection) VALUES ( 65,trim('Programación pin'), 'TbEbrsProgrammingPin');
INSERT INTO base.tb_ifeb_bi_event(event_cod, event_name, collection) VALUES ( 66,trim('Programación basica'), 'TbEbrsProgramminBasic');
INSERT INTO base.tb_ifeb_bi_event(event_cod, event_name, collection) VALUES ( 67,trim('Programación ip y puerto destino'), 'TbEbrsProgrammingIpAndPort');
INSERT INTO base.tb_ifeb_bi_event(event_cod, event_name, collection) VALUES ( 68,trim('Programación APN'), 'TbEbrsProgramminApn');
INSERT INTO base.tb_ifeb_bi_event(event_cod, event_name, collection) VALUES ( 69,trim('Interrogación APN'), 'TbEbrsQuestionApn');
INSERT INTO base.tb_ifeb_bi_event(event_cod, event_name, collection) VALUES ( 70,trim('Interrogación IP'), 'TbEbrsQuestionIp');
INSERT INTO base.tb_ifeb_bi_event(event_cod, event_name, collection) VALUES ( 71,trim('Lectura de ruta'), 'TbEbrsReadRoute');
INSERT INTO base.tb_ifeb_bi_event(event_cod, event_name, collection) VALUES ( 72,trim('Programación de ruta'), 'TbEbrsProgrammingRoute');
INSERT INTO base.tb_ifeb_bi_event(event_cod, event_name, collection) VALUES ( 73,trim('Consulta programación'), 'TbEbrsScheduleQuery');
INSERT INTO base.tb_ifeb_bi_event(event_cod, event_name, collection) VALUES ( 74,trim('Respuesta consulta programación'), 'TbEbrsAnswerQuestionProgramming');
INSERT INTO base.tb_ifeb_bi_event(event_cod, event_name, collection) VALUES ( 75,trim('Programacion terminal'), 'TbEbrsProgrammingTerminal');
INSERT INTO base.tb_ifeb_bi_event(event_cod, event_name, collection) VALUES ( 76,trim('Programación mensajes pregrabados'), 'TbEbrsMessageProgramming');
INSERT INTO base.tb_ifeb_bi_event(event_cod, event_name, collection) VALUES ( 77,trim('Lectura mensajes INBOX'), 'TbEbrsReadingMessagesInbox');
INSERT INTO base.tb_ifeb_bi_event(event_cod, event_name, collection) VALUES ( 79,trim(' Exceso de Velocidad Zona Equipo'), 'TbEbrsSpeedingZoneDevice');
INSERT INTO base.tb_ifeb_bi_event(event_cod, event_name, collection) VALUES ( 80,trim('Programación cel'), 'TbEbrsProgrammingCellular');
INSERT INTO base.tb_ifeb_bi_event(event_cod, event_name, collection) VALUES ( 81,trim('Conf Programación cel'), 'TbEbrsConfProgrammingCellular');
INSERT INTO base.tb_ifeb_bi_event(event_cod, event_name, collection) VALUES ( 82,trim('Programación geofences'), 'TbEbrsProgrammingGeofences');
INSERT INTO base.tb_ifeb_bi_event(event_cod, event_name, collection) VALUES ( 86,trim('Programación Parámetros extendidos 2'), 'TbEbrsProgrammingExtendedParametersTwo');
INSERT INTO base.tb_ifeb_bi_event(event_cod, event_name, collection) VALUES ( 100,trim('Por distancia recorrida'), 'TbEbrsByDistanceTraveled');
INSERT INTO base.tb_ifeb_bi_event(event_cod, event_name, collection) VALUES ( 101,trim('Evento sensor'), 'TbEbrsSensorEvent');
INSERT INTO base.tb_ifeb_bi_event(event_cod, event_name, collection) VALUES ( 128,trim('Ping'), 'TbEbrsPing');
INSERT INTO base.tb_ifeb_bi_event(event_cod, event_name, collection) VALUES ( 129,trim('Versión'), 'TbEbrsVersion');
INSERT INTO base.tb_ifeb_bi_event(event_cod, event_name, collection) VALUES ( 131,trim('Paquete'), 'TbEbrspackage');
INSERT INTO base.tb_ifeb_bi_event(event_cod, event_name, collection) VALUES ( 132,trim('Pin'), 'TbEbrsPin');
INSERT INTO base.tb_ifeb_bi_event(event_cod, event_name, collection) VALUES ( 133,trim('Cobertura'), 'TbEbrsCoverage');
INSERT INTO base.tb_ifeb_bi_event(event_cod, event_name, collection) VALUES ( 134,trim('Mensaje'), 'TbEbrsMessages');
INSERT INTO base.tb_ifeb_bi_event(event_cod, event_name, collection) VALUES ( 135,trim('Mensaje skytrack'), 'TbEbrsMessageSkytrack');
INSERT INTO base.tb_ifeb_bi_event(event_cod, event_name, collection) VALUES ( 136,trim(' Ralenti'), 'TbEbrsRalenti');
INSERT INTO base.tb_ifeb_bi_event(event_cod, event_name, collection) VALUES ( 137,trim(' Horometro'), 'TbEbrsHorometro');
INSERT INTO base.tb_ifeb_bi_event(event_cod, event_name, collection) VALUES ( 138,trim('Prog Bas SMS = 138'), 'TbEbrsProgBasSms');
INSERT INTO base.tb_ifeb_bi_event(event_cod, event_name, collection) VALUES ( 139,trim('Prog bas SMS = 138 (Paquete RFID)'), 'TbEbrsProgBasSmsPackageRfid');
INSERT INTO base.tb_ifeb_bi_event(event_cod, event_name, collection) VALUES ( 140,trim('Call in = 140'), 'TbEbrsCallInForty');
INSERT INTO base.tb_ifeb_bi_event(event_cod, event_name, collection) VALUES ( 141,trim('Call out'), 'TbEbrsCallOut');
INSERT INTO base.tb_ifeb_bi_event(event_cod, event_name, collection) VALUES ( 142,trim('Ctr volumen'), 'TbEbrsCtrVolume');
INSERT INTO base.tb_ifeb_bi_event(event_cod, event_name, collection) VALUES ( 144,trim(' Mensaje Satelital'), 'TbEbrsSatelliteMessage');
INSERT INTO base.tb_ifeb_bi_event(event_cod, event_name, collection) VALUES ( 145,trim(' GSM GPS Info '), 'TbEbrsGsmGpsInfo');
INSERT INTO base.tb_ifeb_bi_event(event_cod, event_name, collection) VALUES ( 146,trim('Solicitud geoposicionamiento GSM'), 'TbEbrsRequestGeolocationGsm');
INSERT INTO base.tb_ifeb_bi_event(event_cod, event_name, collection) VALUES ( 148,trim('Paquete extendido skytrack'), 'TbEbrsExtendedPackageSkytrack');
INSERT INTO base.tb_ifeb_bi_event(event_cod, event_name, collection) VALUES ( 150,trim('Petición de agenda'), 'TbEbrsAgendaRequest');
INSERT INTO base.tb_ifeb_bi_event(event_cod, event_name, collection) VALUES ( 200,trim('Prog tel call'), 'TbEbrsProgrammingTelCall');
INSERT INTO base.tb_ifeb_bi_event(event_cod, event_name, collection) VALUES ( 201,trim('Prog tel1'), 'TbEbrsProgrammingTelOne');
INSERT INTO base.tb_ifeb_bi_event(event_cod, event_name, collection) VALUES ( 202,trim('Prog tel2'), 'TbEbrsProgrammingTelTwo');
INSERT INTO base.tb_ifeb_bi_event(event_cod, event_name, collection) VALUES ( 203,trim('Prog tel3'), 'TbEbrsProgrammingTelTree');
INSERT INTO base.tb_ifeb_bi_event(event_cod, event_name, collection) VALUES ( 204,trim('Prog tel driver'), 'TbEbrsProgrammingTelDriver');
INSERT INTO base.tb_ifeb_bi_event(event_cod, event_name, collection) VALUES ( 238,trim('Interrogación posición WEB'), 'TbEbrsPositionInterrogationWeb');
INSERT INTO base.tb_ifeb_bi_event(event_cod, event_name, collection) VALUES ( 239,trim('Interrogación posición llamada'), 'TbEbrsCallInterrogationPosition');
INSERT INTO base.tb_ifeb_bi_event(event_cod, event_name, collection) VALUES ( 253,trim(' Apagado Remoto Activado'), 'TbEbrsOffRemoteOn');
INSERT INTO base.tb_ifeb_bi_event(event_cod, event_name, collection) VALUES ( 264,trim(' Deteccion de Jamming '), 'TbEbrsJammingIndication');
INSERT INTO base.tb_ifeb_bi_event(event_cod, event_name, collection) VALUES ( 1000,trim(' Alarmas Mantenimientos '), 'TbEbrsVerificationSicomError');
INSERT INTO base.tb_ifeb_bi_event(event_cod, event_name, collection) VALUES ( 1034,trim(' Sleep Mode '), 'TbEbrsModeSpleep');
INSERT INTO base.tb_ifeb_bi_event(event_cod, event_name, collection) VALUES ( 1073,trim(' Reporte de alarma externa'), 'TbEbrsExternalAlarmReport');
INSERT INTO base.tb_ifeb_bi_event(event_cod, event_name, collection) VALUES ( 3002,trim(' Exceso de Velocidad Zonas y Rutas'), 'TbEbrsExcessSpeedZoneTeam');
INSERT INTO base.tb_ifeb_bi_event(event_cod, event_name, collection) VALUES ( 3003,trim(' Retraso en ruta programada '), 'TbEbrsProgrammingRouteDelay');
INSERT INTO base.tb_ifeb_bi_event(event_cod, event_name, collection) VALUES ( 3004,trim(' Actividad en horario no permitido'), 'TbEbrsScheduleActivityNotAllowed');
INSERT INTO base.tb_ifeb_bi_event(event_cod, event_name, collection) VALUES ( 3007,trim(' Excede tiempo sin transmitir en Ruta '), 'TbEbrsExceedsTimeWithoutTransmittingInRoute');
INSERT INTO base.tb_ifeb_bi_event(event_cod, event_name, collection) VALUES ( 3008,trim(' Excede tiempo de parada en Ruta'), 'TbEbrsExceedsStopTimeInRoute');
INSERT INTO base.tb_ifeb_bi_event(event_cod, event_name, collection) VALUES ( 3011,trim(' Sin movimiento Ignicion On '), 'TbEbrsNoMovementIgnitionOn');
INSERT INTO base.tb_ifeb_bi_event(event_cod, event_name, collection) VALUES ( 3012,trim(' En movimiento Ignicion On'), 'TbEbrsOnTheMoveIgnitionOn');
INSERT INTO base.tb_ifeb_bi_event(event_cod, event_name, collection) VALUES ( 3013,trim(' Sin movimiento Ignicion Off'), 'TbEbrsNoMovementIgnitionOff');
INSERT INTO base.tb_ifeb_bi_event(event_cod, event_name, collection) VALUES ( 3014,trim(' En movimiento Ignicion Off '), 'TbEbrsWithMovementIgnitionOff');
INSERT INTO base.tb_ifeb_bi_event(event_cod, event_name, collection) VALUES ( 3018,trim(' Tiempo fuera del rango de velocidad'), 'TbEbrsWithinTheSpeedRange');
INSERT INTO base.tb_ifeb_bi_event(event_cod, event_name, collection) VALUES ( 3019,trim(' Fuera del rango de velocidad '), 'TbEbrsOutOfSpeedRange');
INSERT INTO base.tb_ifeb_bi_event(event_cod, event_name, collection) VALUES ( 3020,trim(' Primera localización despues de encendido'), 'TbEbrsFirstLocationAfterPowerOn');
INSERT INTO base.tb_ifeb_bi_event(event_cod, event_name, collection) VALUES ( 3021,trim(' Entrada digital deshabilitada'), 'TbEbrsDigitalInputDisabled');
INSERT INTO base.tb_ifeb_bi_event(event_cod, event_name, collection) VALUES ( 3022,trim(' Entrada digital habilitada '), 'TbEbrsDigitalInputEnabled');
INSERT INTO base.tb_ifeb_bi_event(event_cod, event_name, collection) VALUES ( 3023,trim(' Inicio carga bateria '), 'TbEbrsStartLoadBattery');
INSERT INTO base.tb_ifeb_bi_event(event_cod, event_name, collection) VALUES ( 3024,trim(' Nivel bajo de bateria'), 'TbEbrsLowBattery');
INSERT INTO base.tb_ifeb_bi_event(event_cod, event_name, collection) VALUES ( 3025,trim(' Fin carga de bateria '), 'TbEbrsEndLoadBattery');
INSERT INTO base.tb_ifeb_bi_event(event_cod, event_name, collection) VALUES ( 3026,trim(' Geocerca 0 desactivada '), 'TbEbrsGeofenceCeroInactivated');
INSERT INTO base.tb_ifeb_bi_event(event_cod, event_name, collection) VALUES ( 3027,trim(' Geocerca 0 activada'), 'TbEbrsGeofenceCeroActivated');
INSERT INTO base.tb_ifeb_bi_event(event_cod, event_name, collection) VALUES ( 3028,trim(' Estado antena gps'), 'TbEbrsExternalAntenna');
INSERT INTO base.tb_ifeb_bi_event(event_cod, event_name, collection) VALUES ( 3029,trim(' Equipo encendido '), 'TbEbrsOnDevice');
INSERT INTO base.tb_ifeb_bi_event(event_cod, event_name, collection) VALUES ( 3030,trim(' Equipo apagado '), 'TbEbrsOffDevice');
INSERT INTO base.tb_ifeb_bi_event(event_cod, event_name, collection) VALUES ( 3031,trim(' Conexión a GPRS'), 'TbEbrsConectionGprs');
INSERT INTO base.tb_ifeb_bi_event(event_cod, event_name, collection) VALUES ( 3032,trim(' Conexión alimentacion externa'), 'TbEbrsExternalPowerConnection');
INSERT INTO base.tb_ifeb_bi_event(event_cod, event_name, collection) VALUES ( 3033,trim(' Desconexión alimentacion externa '), 'TbEbrsDisconnectExternalPower');
INSERT INTO base.tb_ifeb_bi_event(event_cod, event_name, collection) VALUES ( 3034,trim(' Centro de geocerca 0 '), 'TbEbrsGeocachingCenterCero');
INSERT INTO base.tb_ifeb_bi_event(event_cod, event_name, collection) VALUES ( 3058,trim(' Estado de bateria externa'), 'TbEbrsExternalBatteryStatus');
INSERT INTO base.tb_ifeb_bi_event(event_cod, event_name, collection) VALUES ( 3087,trim(' Estado OBD '), 'TbEbrsInformationCanbus');
INSERT INTO base.tb_ifeb_bi_event(event_cod, event_name, collection) VALUES ( 3089,trim(' Alarma Perdida Combustible '), 'TbEbrsConsumptionAlarm');
INSERT INTO base.tb_ifeb_bi_event(event_cod, event_name, collection) VALUES ( 4000,trim(' Sobrepaso Superior temp1 '), 'TbEbrsTopOverTemp1');
INSERT INTO base.tb_ifeb_bi_event(event_cod, event_name, collection) VALUES ( 4001,trim(' Sobrepaso Inferior temp1 '), 'TbEbrsLowerOverpassTempOne');
INSERT INTO base.tb_ifeb_bi_event(event_cod, event_name, collection) VALUES ( 4002,trim(' Sobrepaso Superior temp2 '), 'TbEbrsTopOverrideTemp2');
INSERT INTO base.tb_ifeb_bi_event(event_cod, event_name, collection) VALUES ( 4003,trim(' Sobrepaso Inferior temp2 '), 'TbEbrsLowerOverpassTempTwo');
INSERT INTO base.tb_ifeb_bi_event(event_cod, event_name, collection) VALUES ( 4004,trim(' Sensor de Temperatura dentro del Rango temp1 '), 'TbEbrsTemperatureSensorWithinRangeTempOne');
INSERT INTO base.tb_ifeb_bi_event(event_cod, event_name, collection) VALUES ( 4005,trim(' Sensor de Temperatura dentro del Rango temp2 '), 'TbEbrsTemperatureSensorWithinRangeTempTwo');
INSERT INTO base.tb_ifeb_bi_event(event_cod, event_name, collection) VALUES ( 4006,trim(' Conductor Autorizado '), 'TbEbrsAuthorizedDriver');
INSERT INTO base.tb_ifeb_bi_event(event_cod, event_name, collection) VALUES ( 4014,trim(' Combinacion 1 activa '), 'TbEbrsIOCombination1');
INSERT INTO base.tb_ifeb_bi_event(event_cod, event_name, collection) VALUES ( 4015,trim(' Combinacion 2 activa '), 'TbEbrsIOCombination2');
INSERT INTO base.tb_ifeb_bi_event(event_cod, event_name, collection) VALUES ( 4016,trim(' Combinacion 3 activa '), 'TbEbrsIOCombination3');
INSERT INTO base.tb_ifeb_bi_event(event_cod, event_name, collection) VALUES ( 4017,trim(' Combinacion 4 activa '), 'TbEbrsIOCombination4');
INSERT INTO base.tb_ifeb_bi_event(event_cod, event_name, collection) VALUES ( 4018,trim(' Frenada Fuerte '), 'TbEbrsLowSpeedHarshBraking');
INSERT INTO base.tb_ifeb_bi_event(event_cod, event_name, collection) VALUES ( 4019,trim(' Inicia Estado Ralenti'), 'TbEbrsIntoIdlingStatus');
INSERT INTO base.tb_ifeb_bi_event(event_cod, event_name, collection) VALUES ( 4020,trim(' Fin Estado Ralenti '), 'TbEbrsLeaveIdlingStatus');
INSERT INTO base.tb_ifeb_bi_event(event_cod, event_name, collection) VALUES ( 4021,trim(' GPS FIX'), 'TbBscResultStandardLocationGps');
INSERT INTO base.tb_ifeb_bi_event(event_cod, event_name, collection) VALUES ( 4022,trim(' Lectura por Kilometraje'), 'TbBscResultStandardLocationKm');
INSERT INTO base.tb_ifeb_bi_event(event_cod, event_name, collection) VALUES ( 4023,trim(' Lectura Optima '), 'TbBscResultStandardLocationOptima');
INSERT INTO base.tb_ifeb_bi_event(event_cod, event_name, collection) VALUES ( 4024,trim(' Cambio de Rumbo'), 'TbBscResultStandardLocationCourse');
INSERT INTO base.tb_ifeb_bi_event(event_cod, event_name, collection) VALUES ( 4025,trim(' Aceleracion Fuerte '), 'TbEbrsLowSpeedHarshAcceleration');
INSERT INTO base.tb_ifeb_bi_event(event_cod, event_name, collection) VALUES ( 4036,trim(' Puesta en marcha del Vehículo'), 'TbEbrsStartVehicle');
INSERT INTO base.tb_ifeb_bi_event(event_cod, event_name, collection) VALUES ( 4037,trim(' Vehículo detenido'), 'TbEbrsStopVehicle');
INSERT INTO base.tb_ifeb_bi_event(event_cod, event_name, collection) VALUES ( 4038,trim(' Perdida de señal GPS '), 'TbEbrsSignalStatusLost');
INSERT INTO base.tb_ifeb_bi_event(event_cod, event_name, collection) VALUES ( 4039,trim(' Señal GPS Recuperada '), 'TbEbrsSignalStatusRecovery');
INSERT INTO base.tb_ifeb_bi_event(event_cod, event_name, collection) VALUES ( 4041,trim(' Lectura por Distancia o Tiempo '), 'TbBscResultStandardLocationTime');
INSERT INTO base.tb_ifeb_bi_event(event_cod, event_name, collection) VALUES ( 4042,trim(' Detención Prolongada '), 'TbEbrsLongStopVehicle');
INSERT INTO base.tb_ifeb_bi_event(event_cod, event_name, collection) VALUES ( 5000,trim(' Frenada rango de vel bajo'), 'TbEbrsBrakingLowSpeedRange');
INSERT INTO base.tb_ifeb_bi_event(event_cod, event_name, collection) VALUES ( 5001,trim(' Acelerada rango vel bajo '), 'TbEbrsAcceleratedLowRange');
INSERT INTO base.tb_ifeb_bi_event(event_cod, event_name, collection) VALUES ( 5002,trim(' Frenada rango medio'), 'TbEbrsBrakingLowRange');
INSERT INTO base.tb_ifeb_bi_event(event_cod, event_name, collection) VALUES ( 5003,trim(' Acelerada rango medio'), 'TbEbrsAcceleratedAverageRange');
INSERT INTO base.tb_ifeb_bi_event(event_cod, event_name, collection) VALUES ( 5004,trim(' Frenada rango alto '), 'TbEbrsHighBrakingRange');
INSERT INTO base.tb_ifeb_bi_event(event_cod, event_name, collection) VALUES ( 5005,trim(' Acelerada rango alto '), 'TbEbrsAcceleratedHighRange');
INSERT INTO base.tb_ifeb_bi_event(event_cod, event_name, collection) VALUES ( 5007,trim(' Arrancada Tarjeta Sensor '), 'TbEbrsSensorCardStarter');
INSERT INTO base.tb_ifeb_bi_event(event_cod, event_name, collection) VALUES ( 5008,trim(' Frenada y Detección de Curva Brusca'), 'TbEbrsBrakingAndSharpCurveDetection');
INSERT INTO base.tb_ifeb_bi_event(event_cod, event_name, collection) VALUES ( 5009,trim(' Aceleración y Detección de Curva Brusca'), 'TbEbrsAccelerationAndSharpCurveDetection');
INSERT INTO base.tb_ifeb_bi_event(event_cod, event_name, collection) VALUES ( 5010,trim(' Comportamiento Brusco'), 'TbEbrsAbruptBehavior');
INSERT INTO base.tb_ifeb_bi_event(event_cod, event_name, collection) VALUES ( 5011,trim(' Cierre Puerta Carga'), 'TbEbrsDigitalInputsCloseLoadingDoor');
INSERT INTO base.tb_ifeb_bi_event(event_cod, event_name, collection) VALUES ( 5020,trim(' Cinturón desactivado '), 'TbEbrsStartMovement');
INSERT INTO base.tb_ifeb_bi_event(event_cod, event_name, collection) VALUES ( 5021,trim('Fin de Movimiento'), 'TbEbrsFinishMovement');
INSERT INTO base.tb_ifeb_bi_event(event_cod, event_name, collection) VALUES ( 3413000,trim(' Mensaje o accion 0 '), 'TbEbrsMessageOrActionCero');
INSERT INTO base.tb_ifeb_bi_event(event_cod, event_name, collection) VALUES ( 3413001,trim(' Mensaje o accion 1 '), 'TbEbrsMessageOrActionOne');
INSERT INTO base.tb_ifeb_bi_event(event_cod, event_name, collection) VALUES ( 3413002,trim(' Mensaje o accion 2 '), 'TbEbrsMessageOrActionTwo');
INSERT INTO base.tb_ifeb_bi_event(event_cod, event_name, collection) VALUES ( 3413003,trim(' Mensaje o accion 3 '), 'TbEbrsMessageOrActionTree');
INSERT INTO base.tb_ifeb_bi_event(event_cod, event_name, collection) VALUES ( 3413004,trim(' Mensaje o accion 4 '), 'TbEbrsMessageOrActionFour');
INSERT INTO base.tb_ifeb_bi_event(event_cod, event_name, collection) VALUES ( 3413005,trim(' Mensaje o accion 5 '), 'TbEbrsMessageOrActionFive');
INSERT INTO base.tb_ifeb_bi_event(event_cod, event_name, collection) VALUES ( 80001,trim('Registro manual de Pasajero'), 'TbEbrsRegisterManualStudent');
INSERT INTO base.tb_ifeb_bi_event(event_cod, event_name, collection) VALUES ( 80002,trim('Registro de Pasajero'), 'TbEbrsRegisterStudent');
INSERT INTO base.tb_ifeb_bi_event(event_cod, event_name, collection) VALUES ( 80003,trim('Inicio de transporte'), 'TbEbrsStartTransport');
INSERT INTO base.tb_ifeb_bi_event(event_cod, event_name, collection) VALUES ( 80004,trim('Fin de transporte'), 'TbEbrsEndTransport');
INSERT INTO base.tb_ifeb_bi_event(event_cod, event_name, collection) VALUES ( 90001,trim('Aproximación a zona fronteriza'), 'TbEbrsApproachesBorderArea');
INSERT INTO base.tb_ifeb_bi_event(event_cod, event_name, collection) VALUES ( 90002,trim('Aproximación a hito'), 'TbEbrsApproachesMilestone');
INSERT INTO base.tb_ifeb_bi_event(event_cod, event_name, collection) VALUES ( 90003,trim('Entrada a polígono'), 'TbEbrsEntrancePolygon');
INSERT INTO base.tb_ifeb_bi_event(event_cod, event_name, collection) VALUES ( 90004,trim('Salida de ruta'), 'TbEbrsExitPath');
INSERT INTO base.tb_ifeb_bi_event(event_cod, event_name, collection) VALUES ( 90005,trim('Salida de Polígono'), 'TbEbrsExitPolygon');
INSERT INTO base.tb_ifeb_bi_event(event_cod, event_name, collection) VALUES ( 90006,trim('Entrada a geocerca'), 'TbEbrsGeofenceCircularDrive');
INSERT INTO base.tb_ifeb_bi_event(event_cod, event_name, collection) VALUES ( 90007,trim('Salida de geocerca'), 'TbEbrsGeofenceCircularOutlet');
INSERT INTO base.tb_ifeb_bi_event(event_cod, event_name, collection) VALUES ( 90008,trim('Exceso de velocidad en geocerca'), 'TbEbrsSpeedingCircularPolygon');
INSERT INTO base.tb_ifeb_bi_event(event_cod, event_name, collection) VALUES ( 90009,trim('Exceso de velocidad en ruta'), 'TbEbrsSpeedingOnRoute');
INSERT INTO base.tb_ifeb_bi_event(event_cod, event_name, collection) VALUES ( 90010,trim('Exceso de velocidad en Polígono'), 'TbEbrsSpeedingPolygon');
INSERT INTO base.tb_ifeb_bi_event(event_cod, event_name, collection) VALUES ( 90011,trim('Parada del vehículo en polígono'), 'TbEbrsStopPolygon');
INSERT INTO base.tb_ifeb_bi_event(event_cod, event_name, collection) VALUES ( 90012,trim('Parada del vehículo en geocerca'), 'TbEbrsStopVehicleCircularPolygon');
INSERT INTO base.tb_ifeb_bi_event(event_cod, event_name, collection) VALUES ( 90013,trim('Tiempo de permanecía en ruta'), 'TbEbrsTimeSpentAtCheckpoint');
INSERT INTO base.tb_ifeb_bi_event(event_cod, event_name, collection) VALUES ( 90014,trim('Tiempo de permanencia en geocerca'), 'TbEbrsTimeSpentCircularPolygon');
INSERT INTO base.tb_ifeb_bi_event(event_cod, event_name, collection) VALUES ( 90015,trim('Tiempo de permanencia en polígono'), 'TbEbrsTimeSpentPolygon');
INSERT INTO base.tb_ifeb_bi_event(event_cod, event_name, collection) VALUES ( 90016,trim('Batería baja virtual'), 'TbEbrsVirtualLowBattery');
INSERT INTO base.tb_ifeb_bi_event(event_cod, event_name, collection) VALUES ( 90017,trim('Exceso de velocidad virtual'), 'TbEbrsVirtualSpeeding');
INSERT INTO base.tb_ifeb_bi_event(event_cod, event_name, collection) VALUES ( 90018,trim('Parada de vehículo virtual'), 'TbEbrsVirtualStopVehicle');

